name: golangci-lint
on: [pull_request]
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [api, approval-service, cli, configuration-service, distributor, helm-service, jmeter-service, lighthouse-service, mongodb-datastore, remediation-service, secret-service, statistics-service]
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.svc }}
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ${{ matrix.svc }}
          args: --tests=false
          github-token: $${{ secrets.GITHUB_TOKEN }}
