name: golangci-lint
on: [pull_request]
jobs:
  golangci-secret-service:
    name: lint/secret-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: secret-service
          github-token: ${{ secrets.KEPTN_KEPTN_GITHUB_TOKEN }}
  golangci-distributor:
    name: lint/distributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: distributor
          github-token: ${{ secrets.KEPTN_KEPTN_GITHUB_TOKEN }}
