name: golangci-lint
on: [pull_request]
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [ secret-service, distributor]
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.svc }}
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ${{ matrix.svc }}
          args: --tests=false
          github-token: $${{ secrets.GITHUB_TOKEN }}
