name: golangci-lint
on: [pull_request]
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint/secret-service
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: secret-service
          github-token: $${{ secrets.GITHUB_TOKEN }}
      - name: lint/distributor
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: distributor
          github-token: $${{ secrets.GITHUB_TOKEN }}
